/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.SQLException;
import javax.swing.JTable;
import java.sql.ResultSet;
import java.util.Vector;
import java.awt.CardLayout; // CRITICAL: This fixes your previous error
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class AccountManagerForm extends javax.swing.JFrame {
    BankSystems bankSystems = new BankSystems();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccountManagerForm.class.getName());

    /**
     * Creates new form AccountManagerForm
     */
    public AccountManagerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Parent = new javax.swing.JPanel();
        Customer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbAccType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtAccountID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccounts = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        Transaction = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cmbSelectAcc = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnDeposit = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnViewHistory = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtAccountId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecentTrans = new javax.swing.JTable();
        History = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtFilterID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cmbFilterType = new javax.swing.JComboBox<>();
        btnApplyFilter = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFullHistory = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BANKING SYSTEMS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(276, 6, 350, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Customer");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 70, 220, 40);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Transaction");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);
        jButton2.setBounds(340, 70, 230, 40);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("History");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3);
        jButton3.setBounds(630, 70, 230, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -1, 900, 120);

        Parent.setBackground(new java.awt.Color(204, 255, 255));
        Parent.setLayout(new java.awt.CardLayout());

        Customer.setBackground(new java.awt.Color(153, 255, 255));
        Customer.setPreferredSize(new java.awt.Dimension(900, 530));
        Customer.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer & Account Management");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(17, 6, 350, 40);

        Customer.add(jPanel2);
        jPanel2.setBounds(262, 6, 380, 50);

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("First Name:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 50, 90, 30);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 90, 81, 30);

        txtFirstName.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(txtFirstName);
        txtFirstName.setBounds(130, 50, 110, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Last Name:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(250, 50, 80, 30);

        txtLastName.setBackground(new java.awt.Color(204, 204, 204));
        txtLastName.addActionListener(this::txtLastNameActionPerformed);
        jPanel3.add(txtLastName);
        txtLastName.setBounds(330, 50, 100, 30);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Phone:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 130, 70, 30);

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(txtEmail);
        txtEmail.setBounds(130, 90, 250, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Account Type:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 170, 100, 30);

        cmbAccType.setBackground(new java.awt.Color(204, 204, 204));
        cmbAccType.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cmbAccType.setForeground(new java.awt.Color(0, 0, 0));
        cmbAccType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings", "Current", " ", " " }));
        jPanel3.add(cmbAccType);
        cmbAccType.setBounds(130, 170, 100, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Balance:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(240, 170, 70, 30);

        txtBalance.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(txtBalance);
        txtBalance.setBounds(330, 170, 100, 30);

        txtPhone.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(txtPhone);
        txtPhone.setBounds(130, 130, 200, 30);

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Account ID:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(20, 10, 90, 30);

        txtAccountID.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountID.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txtAccountID);
        txtAccountID.setBounds(130, 10, 200, 30);

        Customer.add(jPanel3);
        jPanel3.setBounds(10, 70, 440, 220);

        tblAccounts.setBackground(new java.awt.Color(204, 204, 204));
        tblAccounts.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblAccounts.setForeground(new java.awt.Color(0, 0, 0));
        tblAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Acc ID", "First Name", "Last Name", "Email", "Phone Number", "Acc Type", "Balance"
            }
        ));
        jScrollPane1.setViewportView(tblAccounts);

        Customer.add(jScrollPane1);
        jScrollPane1.setBounds(10, 300, 880, 170);

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Search:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 10, 60, 30);

        txtSearch.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.add(txtSearch);
        txtSearch.setBounds(80, 10, 220, 30);

        btnSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 0, 0));
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        jPanel4.add(btnSearch);
        btnSearch.setBounds(310, 10, 100, 30);

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        jPanel4.add(btnAdd);
        btnAdd.setBounds(20, 70, 100, 40);

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel4.add(btnUpdate);
        btnUpdate.setBounds(160, 70, 100, 40);

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        jPanel4.add(btnDelete);
        btnDelete.setBounds(300, 70, 100, 40);

        btnView.setBackground(new java.awt.Color(204, 204, 204));
        btnView.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(0, 0, 0));
        btnView.setText("VIEW");
        btnView.addActionListener(this::btnViewActionPerformed);
        jPanel4.add(btnView);
        btnView.setBounds(160, 150, 100, 40);

        Customer.add(jPanel4);
        jPanel4.setBounds(470, 70, 420, 220);

        Parent.add(Customer, "card2");

        Transaction.setBackground(new java.awt.Color(153, 255, 255));
        Transaction.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(51, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Transaction Management");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(18, 6, 360, 40);

        Transaction.add(jPanel5);
        jPanel5.setBounds(250, 6, 400, 50);

        jPanel6.setBackground(new java.awt.Color(0, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Select Account:");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(20, 10, 120, 40);

        cmbSelectAcc.setBackground(new java.awt.Color(204, 204, 204));
        cmbSelectAcc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbSelectAcc.setForeground(new java.awt.Color(0, 0, 0));
        cmbSelectAcc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings", "Current", " " }));
        jPanel6.add(cmbSelectAcc);
        cmbSelectAcc.setBounds(150, 10, 210, 40);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Enter Amount:");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(380, 10, 100, 40);

        txtAmount.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.add(txtAmount);
        txtAmount.setBounds(510, 10, 190, 40);

        btnDeposit.setBackground(new java.awt.Color(204, 204, 204));
        btnDeposit.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnDeposit.setForeground(new java.awt.Color(0, 0, 0));
        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(this::btnDepositActionPerformed);
        jPanel6.add(btnDeposit);
        btnDeposit.setBounds(50, 120, 150, 40);

        btnWithdraw.setBackground(new java.awt.Color(204, 204, 204));
        btnWithdraw.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnWithdraw.setForeground(new java.awt.Color(0, 0, 0));
        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(this::btnWithdrawActionPerformed);
        jPanel6.add(btnWithdraw);
        btnWithdraw.setBounds(280, 120, 160, 40);

        btnViewHistory.setBackground(new java.awt.Color(204, 204, 204));
        btnViewHistory.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnViewHistory.setForeground(new java.awt.Color(0, 0, 0));
        btnViewHistory.setText("View Transactions");
        btnViewHistory.addActionListener(this::btnViewHistoryActionPerformed);
        jPanel6.add(btnViewHistory);
        btnViewHistory.setBounds(520, 120, 160, 40);

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Account ID:");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(180, 70, 90, 40);

        txtAccountId.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.add(txtAccountId);
        txtAccountId.setBounds(280, 70, 190, 40);

        Transaction.add(jPanel6);
        jPanel6.setBounds(90, 70, 720, 180);

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 0));

        tblRecentTrans.setBackground(new java.awt.Color(204, 204, 204));
        tblRecentTrans.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblRecentTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Account ID", "Type (Dep/With)", "Amount", "Date"
            }
        ));
        jScrollPane2.setViewportView(tblRecentTrans);

        Transaction.add(jScrollPane2);
        jScrollPane2.setBounds(10, 270, 880, 190);

        Parent.add(Transaction, "card3");

        History.setBackground(new java.awt.Color(153, 255, 255));
        History.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(0, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Transaction Logs & History");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(22, 6, 360, 50);

        History.add(jPanel7);
        jPanel7.setBounds(251, 6, 400, 60);

        jPanel8.setBackground(new java.awt.Color(51, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Account ID:");
        jPanel8.add(jLabel14);
        jLabel14.setBounds(20, 10, 100, 40);

        txtFilterID.setBackground(new java.awt.Color(204, 204, 204));
        txtFilterID.setForeground(new java.awt.Color(0, 0, 0));
        jPanel8.add(txtFilterID);
        txtFilterID.setBounds(130, 10, 210, 40);

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Transaction Type:");
        jPanel8.add(jLabel15);
        jLabel15.setBounds(370, 10, 130, 40);

        cmbFilterType.setBackground(new java.awt.Color(204, 204, 204));
        cmbFilterType.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cmbFilterType.setForeground(new java.awt.Color(0, 0, 0));
        cmbFilterType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposit", "Withdraw" }));
        jPanel8.add(cmbFilterType);
        cmbFilterType.setBounds(520, 10, 230, 40);

        btnApplyFilter.setBackground(new java.awt.Color(204, 204, 204));
        btnApplyFilter.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnApplyFilter.setForeground(new java.awt.Color(0, 0, 0));
        btnApplyFilter.setText("Apply Filters");
        btnApplyFilter.addActionListener(this::btnApplyFilterActionPerformed);
        jPanel8.add(btnApplyFilter);
        btnApplyFilter.setBounds(20, 70, 140, 40);

        History.add(jPanel8);
        jPanel8.setBounds(50, 80, 790, 150);

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setForeground(new java.awt.Color(0, 0, 0));

        tblFullHistory.setBackground(new java.awt.Color(204, 204, 204));
        tblFullHistory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblFullHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Account ID", "Transaction Type", "Amount", "Date"
            }
        ));
        jScrollPane3.setViewportView(tblFullHistory);

        History.add(jScrollPane3);
        jScrollPane3.setBounds(20, 250, 860, 210);

        Parent.add(History, "card4");

        getContentPane().add(Parent);
        Parent.setBounds(0, 120, 900, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void btnApplyFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyFilterActionPerformed
        // 1. Get the Account ID from your text field
    String searchID = txtFilterID.getText().trim(); 

    // 2. Clear the table completely before the new search
    // This ensures only "one" search result (or one account's history) shows at a time
    DefaultTableModel model = (DefaultTableModel) tblFullHistory.getModel();
    model.setRowCount(0);

    // 3. Prevent empty searches from crashing
    if (searchID.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter an Account ID to search.");
        return;
    }

    try {
        BankDAO dao = new BankDAO();
        // Use the Filtered method we set up in the DAO
        // We pass "Account ID" as the type so the SQL knows to use: WHERE account_id = ?
        ResultSet rs = dao.getFilteredTransactions("Account ID", searchID);
        
        boolean found = false;
        while (rs != null && rs.next()) {
            found = true;
            Vector<Object> row = new Vector<>();
            row.add(rs.getString("account_id"));
            row.add(rs.getString("transaction_type"));
            row.add(rs.getDouble("amount"));
            row.add(rs.getTimestamp("transaction_date"));
            model.addRow(row);
        }
        
        if (!found) {
            javax.swing.JOptionPane.showMessageDialog(this, "No transactions found for Account ID: " + searchID);
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnApplyFilterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(Customer);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(Transaction);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(History);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        // 1. Collect data from your NEW field
    String id = txtAccountID.getText(); // Now this matches the UI
    String fn = txtFirstName.getText();
    String ln = txtLastName.getText();
    String em = txtEmail.getText();
    String ph = txtPhone.getText();
    String ty = cmbAccType.getSelectedItem().toString();
    String bal = txtBalance.getText();

    // 2. Call your logic
    BankSystems logic = new BankSystems();
    logic.addCustomerAndAccount(id, fn, ln, em, ph, ty, bal);
    
    // 3. Refresh the table
    logic.populateTable(tblAccounts);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = txtAccountID.getText(); 
    String fn = txtFirstName.getText();
    String ln = txtLastName.getText();
    String em = txtEmail.getText();
    String ph = txtPhone.getText();

    if (id.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter an Account ID!");
        return;
    }

    BankSystems logic = new BankSystems();
    // This call will no longer be red/error once you update BankSystems.java
    boolean isUpdated = logic.updateCustomerInfo(id, fn, ln, em, ph);

    if (isUpdated) {
        javax.swing.JOptionPane.showMessageDialog(this, "Success! Record Updated.");
        logic.populateTable(tblAccounts); // Refresh your JTable
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Update Failed. Check Account ID.");
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id = txtAccountID.getText();

    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Select an account or enter an ID first.");
        return;
    }

    // Confirmation Pop-up
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete Account " + id + "?", 
            "Confirm Deletion", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        BankSystems logic = new BankSystems();
        if (logic.deleteAccount(id)) {
            JOptionPane.showMessageDialog(this, "Account deleted successfully.");
            
            // Clear fields and refresh table
            txtAccountID.setText("");
            txtFirstName.setText("");
            txtLastName.setText("");
            logic.populateTable(tblAccounts); 
        } else {
            JOptionPane.showMessageDialog(this, "Delete failed. Account ID not found.");
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:]
        String id = txtAccountID.getText();

    if (id.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter an Account ID!");
        return;
    }

    BankSystems logic = new BankSystems();
    
    // IMPORTANT: Ensure these names (txtFirstName, etc.) match your NetBeans Variable Names
    logic.loadToFields(id, txtFirstName, txtLastName, txtEmail, txtPhone, txtBalance);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtSearch.getText().trim();
    DefaultTableModel model = (DefaultTableModel) tblAccounts.getModel();
    model.setRowCount(0);

    BankDAO dao = new BankDAO();
    try {
        ResultSet rs = dao.searchAccounts(keyword);
        while (rs != null && rs.next()) {
            Vector<Object> row = new Vector<>();
            row.add(rs.getString("account_id"));
            row.add(rs.getString("first_name"));
            row.add(rs.getString("last_name"));
            row.add(rs.getString("email"));
            row.add(rs.getString("phone"));
            row.add(rs.getString("account_type"));
            row.add(rs.getDouble("balance"));
            model.addRow(row);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
        String id = txtAccountId.getText().trim();
    String amount = txtAmount.getText().trim();
    String type = cmbSelectAcc.getSelectedItem().toString(); // e.g., "Savings"

    // 1. Perform the math and DB update
    bankSystems.performTransaction(id, type, amount, "DEPOSIT");

    // 2. Automatic refresh: the table updates immediately
    refreshTransactionTable();
    
    // Optional: Clear amount field for next use
    txtAmount.setText("");
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        // TODO add your handling code here:
        String id = txtAccountId.getText().trim();
    String amount = txtAmount.getText().trim();
    String type = cmbSelectAcc.getSelectedItem().toString();

    // 1. Perform the math and DB update
    bankSystems.performTransaction(id, type, amount, "WITHDRAW");

    // 2. Automatic refresh
    refreshTransactionTable();
    
    txtAmount.setText("");
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void handleTransactionResult(String result) {
    switch (result) {
        case "SUCCESS" -> {
            JOptionPane.showMessageDialog(this, "Transaction Successful!");
            txtAmount.setText("");
            // Optional: refresh your transaction table here
        }
        case "NOT_FOUND" -> JOptionPane.showMessageDialog(this, "Error: Account ID and Type do not match.");
        case "NO_FUNDS" -> JOptionPane.showMessageDialog(this, "Error: Insufficient balance.");
        default -> JOptionPane.showMessageDialog(this, "Database Error occurred.");
    }
}
    
    private void btnViewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHistoryActionPerformed
        // TODO add your handling code here:
        refreshTransactionTable();
    JOptionPane.showMessageDialog(this, "Transaction history updated.");
    }//GEN-LAST:event_btnViewHistoryActionPerformed

    private void refreshTransactionTable() {
    DefaultTableModel model = (DefaultTableModel) tblRecentTrans.getModel();
    model.setRowCount(0); 

    try {
        BankDAO dao = new BankDAO();
        ResultSet rs = dao.getAllTransactions();
        
        while (rs != null && rs.next()) {
            Vector<Object> row = new Vector<>();
            
            // Column 0: Transaction ID (The 1, 2, 3, 4, 5 on the far left)
            row.add(rs.getInt("transaction_id"));
            
            // Column 1: Account ID (e.g., 1001, 1002)
            row.add(rs.getString("account_id"));
            
            // Column 2: Transaction Type (Withdraw / Deposit)
            row.add(rs.getString("transaction_type"));
            
            // Column 3: Amount (e.g., 200.0)
            row.add(rs.getDouble("amount"));
            
            // Column 4: Date
            row.add(rs.getTimestamp("transaction_date"));
            
            model.addRow(row);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AccountManagerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Customer;
    private javax.swing.JPanel History;
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel Transaction;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnApplyFilter;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnViewHistory;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JComboBox<String> cmbAccType;
    private javax.swing.JComboBox<String> cmbFilterType;
    private javax.swing.JComboBox<String> cmbSelectAcc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblAccounts;
    private javax.swing.JTable tblFullHistory;
    private javax.swing.JTable tblRecentTrans;
    private javax.swing.JTextField txtAccountID;
    private javax.swing.JTextField txtAccountId;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFilterID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
